export const defaultTimeZones = [
  { group: 'United States of America', label: 'Eastern Time Zone', value: 'America/New_York' },
  { group: 'United States of America', label: 'Central Time Zone', value: 'America/Chicago' },
  { group: 'United States of America', label: 'Mountain Time Zone', value: 'America/Denver' },
  { group: 'United States of America', label: 'Mountain Time Zone (no DST)', value: 'America/Phoenix' },
  { group: 'United States of America', label: 'Pacific Time Zone', value: 'America/Los_Angeles' },
  { group: 'United States of America', label: 'Alaska Time Zone', value: 'America/Anchorage' },
  { group: 'United States of America', label: 'Hawaii-Aleutian Time Zone', value: 'America/Adak' },
  { group: 'United States of America', label: 'Hawaii-Aleutian Time Zone (no DST)', value: 'Pacific/Honolulu' },
  { label: 'Niue Time', value: 'Pacific/Niue' },
  { label: 'Samoa Time', value: 'Pacific/Midway' },
  { label: 'Cook Islands Time', value: 'Pacific/Rarotonga' },
  { label: 'Tahiti Time', value: 'Pacific/Tahiti' },
  { label: 'Marquesas Time', value: 'Pacific/Marquesas' },
  { label: 'Gambier Time', value: 'Pacific/Gambier' },
  { label: 'Pitcairn Time', value: 'Pacific/Pitcairn' },
  { label: 'Mexican Pacific Time', value: 'America/Hermosillo' },
  { label: 'Mountain Time', value: 'America/Dawson_Creek' },
  { label: 'Central Time', value: 'America/Belize' },
  { label: 'Galapagos Time', value: 'Pacific/Galapagos' },
  { label: 'Acre Time', value: 'America/Rio_Branco' },
  { label: 'Colombia Time', value: 'America/Bogota' },
  { label: 'Easter Island Time', value: 'Pacific/Easter' },
  { label: 'Eastern Time', value: 'America/Atikokan' },
  { label: 'Ecuador Time', value: 'America/Guayaquil' },
  { label: 'Peru Time', value: 'America/Lima' },
  { label: 'Amazon Time', value: 'America/Manaus' },
  { label: 'Atlantic Time', value: 'America/St_Kitts' },
  { label: 'Bolivia Time', value: 'America/La_Paz' },
  { label: 'Cuba Time', value: 'America/Havana' },
  { label: 'Guyana Time', value: 'America/Guyana' },
  { label: 'Venezuela Time', value: 'America/Caracas' },
  { label: 'Argentina Time', value: 'America/Argentina/Buenos_Aires' },
  { label: 'Brasilia Time', value: 'America/Sao_Paulo' },
  { label: 'Chile Time', value: 'America/Santiago' },
  { label: 'Falkland Islands Time', value: 'Atlantic/Stanley' },
  { label: 'French Guiana Time', value: 'America/Cayenne' },
  { label: 'Paraguay Time', value: 'America/Asuncion' },
  { label: 'Suriname Time', value: 'America/Paramaribo' },
  { label: 'Uruguay Time', value: 'America/Montevideo' },
  { label: 'Newfoundland Time', value: 'America/St_Johns' },
  { label: 'Fernando de Noronha Time', value: 'America/Noronha' },
  { label: 'South Georgia Time', value: 'Atlantic/South_Georgia' },
  { label: 'St. Pierre & Miquelon Time', value: 'America/Miquelon' },
  { label: 'West Greenland Time', value: 'America/Godthab' },
  { label: 'Cape Verde Time', value: 'Atlantic/Cape_Verde' },
  { label: 'Azores Time', value: 'Atlantic/Azores' },
  { label: 'East Greenland Time', value: 'America/Scoresbysund' },
  { label: 'Greenwich Mean Time', value: 'Africa/Abidjan' },
  { label: 'Central European Time', value: 'Africa/Algiers' },
  { label: 'West Africa Time', value: 'Africa/Bangui' },
  { label: 'Western European Time', value: 'Atlantic/Canary' },
  { label: 'Central Africa Time', value: 'Africa/Bujumbura' },
  { label: 'East Africa Time', value: 'Africa/Juba' },
  { label: 'Eastern European Time', value: 'Africa/Cairo' },
  { label: 'South Africa Time', value: 'Africa/Johannesburg' },
  { label: 'Arabian Time', value: 'Asia/Kuwait' },
  { label: 'Israel Time', value: 'Asia/Jerusalem' },
  { label: 'Moscow Time', value: 'Europe/Minsk' },
  { label: 'Syowa Time', value: 'Antarctica/Syowa' },
  { label: 'Turkey Time', value: 'Europe/Istanbul' },
  { label: 'Iran Time', value: 'Asia/Tehran' },
  { label: 'Armenia Time', value: 'Asia/Yerevan' },
  { label: 'Azerbaijan Time', value: 'Asia/Baku' },
  { label: 'Georgia Time', value: 'Asia/Tbilisi' },
  { label: 'Gulf Time', value: 'Asia/Dubai' },
  { label: 'Mauritius Time', value: 'Indian/Mauritius' },
  { label: 'Réunion Time', value: 'Indian/Reunion' },
  { label: 'Samara Time', value: 'Europe/Samara' },
  { label: 'Seychelles Time', value: 'Indian/Mahe' },
  { label: 'Afghanistan Time', value: 'Asia/Kabul' },
  { label: 'French Southern & Antarctic Time', value: 'Indian/Kerguelen' },
  { label: 'Maldives Time', value: 'Indian/Maldives' },
  { label: 'Mawson Time', value: 'Antarctica/Mawson' },
  { label: 'Pakistan Time', value: 'Asia/Karachi' },
  { label: 'Tajikistan Time', value: 'Asia/Dushanbe' },
  { label: 'Turkmenistan Time', value: 'Asia/Ashgabat' },
  { label: 'Uzbekistan Time', value: 'Asia/Tashkent' },
  { label: 'West Kazakhstan Time', value: 'Asia/Qyzylorda' },
  { label: 'Yekaterinburg Time', value: 'Asia/Yekaterinburg' },
  { label: 'India Time', value: 'Asia/Colombo' },
  { label: 'Nepal Time', value: 'Asia/Kathmandu' },
  { label: 'Bangladesh Time', value: 'Asia/Dhaka' },
  { label: 'Bhutan Time', value: 'Asia/Thimphu' },
  { label: 'China Time', value: 'Asia/Urumqi' },
  { label: 'East Kazakhstan Time', value: 'Asia/Almaty' },
  { label: 'Indian Ocean Time', value: 'Indian/Chagos' },
  { label: 'Kyrgyzstan Time', value: 'Asia/Bishkek' },
  { label: 'Omsk Time', value: 'Asia/Omsk' },
  { label: 'Vostok Time', value: 'Antarctica/Vostok' },
  { label: 'Cocos Islands Time', value: 'Indian/Cocos' },
  { label: 'Myanmar Time', value: 'Asia/Yangon' },
  { label: 'Christmas Island Time', value: 'Indian/Christmas' },
  { label: 'Davis Time', value: 'Antarctica/Davis' },
  { label: 'Hovd Time', value: 'Asia/Hovd' },
  { label: 'Indochina Time', value: 'Asia/Bangkok' },
  { label: 'Novosibirsk Time', value: 'Asia/Novosibirsk' },
  { label: 'Western Indonesia Time', value: 'Asia/Jakarta' },
  { label: 'Australian Western Time', value: 'Australia/Perth' },
  { label: 'Brunei Darussalam Time', value: 'Asia/Brunei' },
  { label: 'Central Indonesia Time', value: 'Asia/Makassar' },
  { label: 'Hong Kong Time', value: 'Asia/Hong_Kong' },
  { label: 'Irkutsk Time', value: 'Asia/Irkutsk' },
  { label: 'Malaysia Time', value: 'Asia/Kuala_Lumpur' },
  { label: 'Philippine Time', value: 'Asia/Manila' },
  { label: 'Singapore Time', value: 'Asia/Singapore' },
  { label: 'Taipei Time', value: 'Asia/Taipei' },
  { label: 'Ulaanbaatar Time', value: 'Asia/Ulaanbaatar' },
  { label: 'Australian Central Western Time', value: 'Australia/Eucla' },
  { label: 'East Timor Time', value: 'Asia/Dili' },
  { label: 'Eastern Indonesia Time', value: 'Asia/Jayapura' },
  { label: 'Japan Time', value: 'Asia/Tokyo' },
  { label: 'Korean Time', value: 'Asia/Pyongyang' },
  { label: 'Palau Time', value: 'Pacific/Palau' },
  { label: 'Yakutsk Time', value: 'Asia/Chita' },
  { label: 'Australian Central Time', value: 'Australia/Darwin' },
  { label: 'Australian Eastern Time', value: 'Australia/Brisbane' },
  { label: 'Chamorro Time', value: 'Pacific/Guam' },
  { label: 'Chuuk Time', value: 'Pacific/Chuuk' },
  { label: 'Dumont-d’Urville Time', value: 'Antarctica/DumontDUrville' },
  { label: 'Papua New Guinea Time', value: 'Pacific/Port_Moresby' },
  { label: 'Vladivostok Time', value: 'Asia/Vladivostok' },
  { label: 'Bougainville Time', value: 'Pacific/Bougainville' },
  { label: 'Kosrae Time', value: 'Pacific/Kosrae' },
  { label: 'Lord Howe Time', value: 'Australia/Lord_Howe' },
  { label: 'Macquarie Island Time', value: 'Antarctica/Macquarie' },
  { label: 'New Caledonia Time', value: 'Pacific/Noumea' },
  { label: 'Sakhalin Time', value: 'Asia/Sakhalin' },
  { label: 'Solomon Islands Time', value: 'Pacific/Guadalcanal' },
  { label: 'Vanuatu Time', value: 'Pacific/Efate' },
  { label: 'Fiji Time', value: 'Pacific/Fiji' },
  { label: 'Gilbert Islands Time', value: 'Pacific/Tarawa' },
  { label: 'Marshall Islands Time', value: 'Pacific/Majuro' },
  { label: 'Nauru Time', value: 'Pacific/Nauru' },
  { label: 'Norfolk Island Time', value: 'Pacific/Norfolk' },
  { label: 'Petropavlovsk-Kamchatski Time', value: 'Asia/Kamchatka' },
  { label: 'Tuvalu Time', value: 'Pacific/Funafuti' },
  { label: 'Wake Island Time', value: 'Pacific/Wake' },
  { label: 'Wallis & Futuna Time', value: 'Pacific/Wallis' },
  { label: 'Apia Time', value: 'Pacific/Apia' },
  { label: 'New Zealand Time', value: 'Pacific/Auckland' },
  { label: 'Phoenix Islands Time', value: 'Pacific/Enderbury' },
  { label: 'Tokelau Time', value: 'Pacific/Fakaofo' },
  { label: 'Tonga Time', value: 'Pacific/Tongatapu' },
  { label: 'Chatham Time', value: 'Pacific/Chatham' },
  { label: 'Line Islands Time', value: 'Pacific/Kiriti' },
];
