// Database will store valid Timezones; this should be sufficient fallback for now
export const TimezoneOpts: {value: string, text: string}[] = [
  { value:'America/New_York', text:'Eastern Time Zone'},
  { value:'America/Chicago', text:'Central Time Zone'},
  { value:'America/Denver', text:'Mountain Time Zone'},
  { value:'America/Phoenix', text:'Mountain Time Zone (no DST)'},
  { value:'America/Los_Angeles', text:'Pacific Time Zone'},
  { value:'America/Anchorage', text:'Alaska Time Zone'},
  { value:'America/Adak', text:'Hawaii-Aleutian Time Zone'},
  { value:'Pacific/Honolulu', text:'Hawaii-Aleutian Time Zone (no DST)'},
  { value:'Pacific/Niue', text:'Niue Time'},
  { value:'Pacific/Midway', text:'Samoa Time'},
  { value:'Pacific/Rarotonga', text:'Cook Islands Time'},
  { value:'Pacific/Honolulu', text:'Hawaii-Aleutian Time'},
  { value:'Pacific/Tahiti', text:'Tahiti Time'},
  { value:'Pacific/Marquesas', text:'Marquesas Time'},
  { value:'Pacific/Gambier', text:'Gambier Time'},
  { value:'America/Anchorage', text:'Alaska Time'},
  { value:'Pacific/Pitcairn', text:'Pitcairn Time'},
  { value:'America/Hermosillo', text:'Mexican Pacific Time'},
  { value:'America/Dawson_Creek', text:'Mountain Time'},
  { value:'America/Los_Angeles', text:'Pacific Time'},
  { value:'America/Belize', text:'Central Time'},
  { value:'Pacific/Galapagos', text:'Galapagos Time'},
  { value:'America/Rio_Branco', text:'Acre Time'},
  { value:'America/Bogota', text:'Colombia Time'},
  { value:'Pacific/Easter', text:'Easter Island Time'},
  { value:'America/Atikokan', text:'Eastern Time'},
  { value:'America/Guayaquil', text:'Ecuador Time'},
  { value:'America/Lima', text:'Peru Time'},
  { value:'America/Manaus', text:'Amazon Time'},
  { value:'America/St_Kitts', text:'Atlantic Time'},
  { value:'America/La_Paz', text:'Bolivia Time'},
  { value:'America/Havana', text:'Cuba Time'},
  { value:'America/Guyana', text:'Guyana Time'},
  { value:'America/Caracas', text:'Venezuela Time'},
  { value:'America/Argentina Buenos_Aires', text:'Argentina Time'},
  { value:'America/Sao_Paulo', text:'Brasilia Time'},
  { value:'America/Santiago', text:'Chile Time'},
  { value:'Atlantic/Stanley', text:'Falkland Islands Time'},
  { value:'America/Cayenne', text:'French Guiana Time'},
  { value:'America/Asuncion', text:'Paraguay Time'},
  { value:'America/Paramaribo', text:'Suriname Time'},
  { value:'America/Montevideo', text:'Uruguay Time'},
  { value:'America/St_Johns', text:'Newfoundland Time'},
  { value:'America/Noronha', text:'Fernando de Noronha Time'},
  { value:'Atlantic/South_Georgia', text:'South Georgia Time'},
  { value:'America/Miquelon', text:'St. Pierre & Miquelon Time'},
  { value:'America/Godthab', text:'West Greenland Time'},
  { value:'Atlantic/Cape_Verde', text:'Cape Verde Time'},
  { value:'Atlantic/Azores', text:'Azores Time'},
  { value:'America/Scoresbysund', text:'East Greenland Time'},
  { value:'Africa/Abidjan', text:'Greenwich Mean Time'},
  { value:'Africa/Algiers', text:'Central European Time'},
  { value:'Africa/Bangui', text:'West Africa Time'},
  { value:'Atlantic/Canary', text:'Western European Time'},
  { value:'Africa/Bujumbura', text:'Central Africa Time'},
  { value:'Africa/Juba', text:'East Africa Time'},
  { value:'Africa/Cairo', text:'Eastern European Time'},
  { value:'Africa/Johannesburg', text:'South Africa Time'},
  { value:'Asia/Kuwait', text:'Arabian Time'},
  { value:'Asia/Jerusalem', text:'Israel Time'},
  { value:'Europe/Minsk', text:'Moscow Time'},
  { value:'Antarctica/Syowa', text:'Syowa Time'},
  { value:'Europe/Istanbul', text:'Turkey Time'},
  { value:'Asia/Tehran', text:'Iran Time'},
  { value:'Asia/Yerevan', text:'Armenia Time'},
  { value:'Asia/Baku', text:'Azerbaijan Time'},
  { value:'Asia/Tbilisi', text:'Georgia Time'},
  { value:'Asia/Dubai', text:'Gulf Time'},
  { value:'Indian/Mauritius', text:'Mauritius Time'},
  { value:'Indian/Reunion', text:'R\u00e9union Time'},
  { value:'Europe/Samara', text:'Samara Time'},
  { value:'Indian/Mahe', text:'Seychelles Time'},
  { value:'Asia/Kabul', text:'Afghanistan Time'},
  { value:'Indian/Kerguelen', text:'French Southern & Antarctic Time'},
  { value:'Indian/Maldives', text:'Maldives Time'},
  { value:'Antarctica/Mawson', text:'Mawson Time'},
  { value:'Asia/Karachi', text:'Pakistan Time'},
  { value:'Asia/Dushanbe', text:'Tajikistan Time'},
  { value:'Asia/Ashgabat', text:'Turkmenistan Time'},
  { value:'Asia/Tashkent', text:'Uzbekistan Time'},
  { value:'Asia/Qyzylorda', text:'West Kazakhstan Time'},
  { value:'Asia/Yekaterinburg', text:'Yekaterinburg Time'},
  { value:'Asia/Colombo', text:'India Time'},
  { value:'Asia/Kathmandu', text:'Nepal Time'},
  { value:'Asia/Dhaka', text:'Bangladesh Time'},
  { value:'Asia/Thimphu', text:'Bhutan Time'},
  { value:'Asia/Urumqi', text:'China Time'},
  { value:'Asia/Almaty', text:'East Kazakhstan Time'},
  { value:'Indian/Chagos', text:'Indian Ocean Time'},
  { value:'Asia/Bishkek', text:'Kyrgyzstan Time'},
  { value:'Asia/Omsk', text:'Omsk Time'},
  { value:'Antarctica/Vostok', text:'Vostok Time'},
  { value:'Indian/Cocos', text:'Cocos Islands Time'},
  { value:'Asia/Yangon', text:'Myanmar Time'},
  { value:'Indian/Christmas', text:'Christmas Island Time'},
  { value:'Antarctica/Davis', text:'Davis Time'},
  { value:'Asia/Hovd', text:'Hovd Time'},
  { value:'Asia/Bangkok', text:'Indochina Time'},
  { value:'Asia/Novosibirsk', text:'Novosibirsk Time'},
  { value:'Asia/Jakarta', text:'Western Indonesia Time'},
  { value:'Australia/Perth', text:'Australian Western Time'},
  { value:'Asia/Brunei', text:'Brunei Darussalam Time'},
  { value:'Asia/Makassar', text:'Central Indonesia Time'},
  { value:'Asia/Hong_Kong', text:'Hong Kong Time'},
  { value:'Asia/Irkutsk', text:'Irkutsk Time'},
  { value:'Asia/Kuala_Lumpur', text:'Malaysia Time'},
  { value:'Asia/Manila', text:'Philippine Time'},
  { value:'Asia/Singapore', text:'Singapore Time'},
  { value:'Asia/Taipei', text:'Taipei Time'},
  { value:'Asia/Ulaanbaatar', text:'Ulaanbaatar Time'},
  { value:'Australia/Eucla', text:'Australian Central Western Time'},
  { value:'Asia/Dili', text:'East Timor Time'},
  { value:'Asia/Jayapura', text:'Eastern Indonesia Time'},
  { value:'Asia/Tokyo', text:'Japan Time'},
  { value:'Asia/Pyongyang', text:'Korean Time'},
  { value:'Pacific/Palau', text:'Palau Time'},
  { value:'Asia/Chita', text:'Yakutsk Time'},
  { value:'Australia/Darwin', text:'Australian Central Time'},
  { value:'Australia/Brisbane', text:'Australian Eastern Time'},
  { value:'Pacific/Guam', text:'Chamorro Time'},
  { value:'Pacific/Chuuk', text:'Chuuk Time'},
  { value:'Antarctica/DumontDUrville', text:'Dumont-d\u2019Urville Time'},
  { value:'Pacific/Port_Moresby', text:'Papua New Guinea Time'},
  { value:'Asia/Vladivostok', text:'Vladivostok Time'},
  { value:'Pacific/Bougainville', text:'Bougainville Time'},
  { value:'Pacific/Kosrae', text:'Kosrae Time'},
  { value:'Australia/Lord_Howe', text:'Lord Howe Time'},
  { value:'Antarctica/Macquarie', text:'Macquarie Island Time'},
  { value:'Pacific/Noumea', text:'New Caledonia Time'},
  { value:'Asia/Sakhalin', text:'Sakhalin Time'},
  { value:'Pacific/Guadalcanal', text:'Solomon Islands Time'},
  { value:'Pacific/Efate', text:'Vanuatu Time'},
  { value:'Pacific/Fiji', text:'Fiji Time'},
  { value:'Pacific/Tarawa', text:'Gilbert Islands Time'},
  { value:'Pacific/Majuro', text:'Marshall Islands Time'},
  { value:'Pacific/Nauru', text:'Nauru Time'},
  { value:'Pacific/Norfolk', text:'Norfolk Island Time'},
  { value:'Asia/Kamchatka', text:'Petropavlovsk-Kamchatski Time'},
  { value:'Pacific/Funafuti', text:'Tuvalu Time'},
  { value:'Pacific/Wake', text:'Wake Island Time'},
  { value:'Pacific/Wallis', text:'Wallis & Futuna Time'},
  { value:'Pacific/Apia', text:'Apia Time'},
  { value:'Pacific/Auckland', text:'New Zealand Time'},
  { value:'Pacific/Enderbury', text:'Phoenix Islands Time'},
  { value:'Pacific/Fakaofo', text:'Tokelau Time'},
  { value:'Pacific/Tongatapu', text:'Tonga Time'},
  { value:'Pacific/Chatham', text:'Chatham Time'},
  { value:'Pacific/Kiritimati', text:'Line Islands Time'},
];