name: Release SemVer

on: workflow_dispatch

jobs:
  check_authorization:
    name: Check authorization to release new version
    runs-on: ubuntu-latest
    outputs:
      isAuthorized: ${{ steps.check-auth.outputs.is_authorized }}
    steps:
      - name: check-auth
        id: check-auth
        run: echo "is_authorized=${{ contains(secrets.DEPLOYMENT_AUTHORIZED_USERS, github.triggering_actor) }}" >> $GITHUB_OUTPUT
  release:
    name: Release
    needs: check_authorization
    if: needs.check_authorization.outputs.isAuthorized == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: semantic-release
        uses: cycjimmy/semantic-release-action@v3
        id: semver
        env:
          GITHUB_TOKEN: ${{ secrets.LIBREBOT_ACCESS_TOKEN }}
          GIT_AUTHOR_NAME: libretexts-bot
          GIT_AUTHOR_EMAIL: dev@libretexts.org
          GIT_COMMITTER_NAME: libretexts-bot
          GIT_COMMITTER_EMAIL: dev@libretexts.org